server:
  servlet:
    context-path: /caws
spring:
  liquibase:
    change-log: classpath:/db/changelog/liquibase-changelog.xml
  datasource:
    url: ${CAWS_DB_URL:jdbc:postgresql://localhost:5432/caws_db}
    username: ${CAWS_DB_USER:caws_db_user}
    password: ${CAWS_DB_PASSWD:caws_db_passwd}
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  hibernate:
    ddl-auto: validate
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
olx:
  notification:
    recipient_mail: ${MAIL_NOTIFICATION_RECIPIENT}
  max_price_pln: 600_000
  desired_location: Warszawa
caws:
  mail:
    content-check-notification:
      subject:
        pre: "Found searched content for url:"
      text:
        pre: "Searched content:"
  website-parse:
    download:
      timeout-ms: 3000
