version: '3.8'
services:
  caws-db:
    container_name: caws-postgres-db
    image: postgres:16-alpine3.19
    restart: always
    environment:
      POSTGRES_DB: ${CAWS_DB_NAME:-caws_db}
      POSTGRES_USER: ${CAWS_DB_USER:-caws_db_user}
      POSTGRES_PASSWORD: ${CAWS_DB_PASSWD:-caws_db_passwd}
    ports:
      - '5432:5432'
    volumes:
      - caws_db:/var/lib/postgresql/data
volumes:
  caws_db:
    driver: local